### ISSUE TITLE
Config in the config folder don't need to be specified in the recipe.yml

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/saplings-program#1]
This is not required.  Config that is in your recipe's config folder is automatically imported.  The config that you would want to import here would be configuration entities from modules that you enabled.  Think a View from the redirect module, or a Metatag Default from the metatag module.  Simple configuration, usually modulename.settings.yml are always imported also so you can skip those.

The whole import section could be removed.  I don't see anything that isn't already being imported.

```
config:
  import:
    node:
      - node.type.program
    core.base_field_override.node.program.promote: "*"
    core.base_field_override.node.program.status: "*"
    core.entity_form_display.node.program.default: "*"
    core.entity_view_display.node.program.default: "*"
    core.entity_view_display.node.program.hero: "*"
    core.entity_view_display.node.program.teaser: "*"
    field.field.node.program.sa_body: "*"
    field.field.node.program.sa_callout: "*"
    field.field.node.program.sa_hero_cta: "*"
    field.field.node.program.sa_components: "*"
    field.field.node.program.sa_description: "*"
    field.field.node.program.sa_featured_media: "*"
    field.field.node.program.sa_header_position: "*"
    field.field.node.program.sa_hide_header: "*"
    field.field.node.program.sa_include_mute_button: "*"
    field.field.node.program.sa_include_pause_button: "*"
    field.field.node.program.sa_overlay_opacity: "*"
    field.field.node.program.sa_overlay: "*"
    field.field.node.program.sa_robots: "*"
    field.field.node.program.sa_seo_description: "*"
    field.field.node.program.sa_seo_image: "*"
    field.field.node.program.sa_seo_page_title: "*"
    metatag:
      - metatag.metatag_defaults.node__program
```
