### ISSUE TITLE
Question: Why do we need to run the core/recipes/content_editor_role recipe?

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/saplings-program#4]

**Comment by thejimbirch** [comment]
Conversation from Slack yesterday.

> Hello Jim!  Elena mentioned you asked why we have content-editor-role in the program content type recipe.  It is in the Content types recipe too.  I was assuming we were going to make these all stand alones so that they can be installed as needed, even if we won't want the Page and Post content types.  Is that not the case? Or should we also remove that from the Saplings-content-types repo?
> 
> ```
> name: 'Saplings - Content types'
> description: 'Configuration for the Saplings Content types.'
> type: 'Site'
> recipes:
>   - core/recipes/content_editor_role
>   - saplings-content-base
>   - saplings-component-types
> ```


That makes sense to include it the. If you want to grant permissions for the content editor role to use the new content type.

So just applying the content editor role is not enough then. We need to use the set permissions config action to give permissions to that role.

**Comment by thejimbirch** [comment]
Here are some permissions from the saplings-events recipe.  Since the role config files already exist, we use config actions to add the permissions we need. We need to set permissions for anonymous to be able to see published nodes, and for the content editor to manage them.  Administrator role automatically gets all permissions so we don't need to do anything for them.

```
config:
  actions:
    # Set permissions for anonymous role.
    user.role.anonymous:
      # This config action is needed to create the role if it does not exist.
      # If the config action exists, it skips doing anything.
      createIfNotExists:
        id: anonymous
      # This config action sets permissions.
      # You can get the permissions from the user role config in the site you created the content type.
      grantPermissions:
        - 'access_unpublished node event'
    # Set permissions for content editor role.
    user.role.content_editor:
      createIfNotExists:
        id: content_editor
      grantPermissions:
        - 'access_unpublished node event'
        - 'clone event content'
        - 'create event content'
        - 'create terms in sa_event_category'
        - 'delete own event content'
        - 'delete event revisions'
        - 'edit any event content'
        - 'edit own event content'
        - 'edit terms in sa_event_category'
        - 'revert event revisions'
        - 'set event published on date'
        - 'view any unpublished event content'
        - 'view event revisions'
```
