### ISSUE TITLE
Lets use the saplings-fields-seo and saplings-fields-header recipes

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/saplings-program#5]
For consistency and allowing us to add our fields to existing content types, we made these two recipes to add the groups of fields to any content types that exist at the time of application.  If the fields already exist, the content type will be skipped.

## What do these recipes do?

We can use kanopi/saplings-fields-header as our example.  The SEO recipe does that same thing, just with different fields.

1. It applies the saplings-media recipe and installs some modules.
2. It creates the following fields:

```
    - field.storage.node.sa_description
    - field.storage.node.sa_featured_media
    - field.storage.node.sa_header_position
    - field.storage.node.sa_hide_header
    - field.storage.node.sa_include_mute_button
    - field.storage.node.sa_include_pause_button
    - field.storage.node.sa_overlay
```
3. It uses config actions to create field instances (field.field.node.field_name configs for each content type that does not have one)

```
# Add Header fields to all content types that are installed.
    field.storage.node.sa_description:
      addToAllBundles:
        label: 'Description'
        description: 'Use this space to write a short description that is used in teaser cards and social media meta tags.'
```

4. It then sets needed settings on each of those newly created configs.

```
    # To set settings on this fields we need to also hit the field instances
    # after they have been created.
    field.field.node.*.sa_featured_media:
      setSettings:
        handler: 'default:media'
        handler_settings:
          target_bundles:
            image: image
            remote_video: remote_video
            video: video
          sort:
            field: _none
            direction: ASC
          auto_create: false
          auto_create_bundle: image
```

5. It then places the fields on the node edit forms.

```
# Place the fields on the all default node forms.
    core.entity_form_display.node.*.default:
      setComponents:
        -
          name: sa_description
          options:
            type: string_textarea
            weight: 3
            region: content
            settings:
              rows: 5
              placeholder: ''
            third_party_settings: {  }
```

6. Then moves the fields into a field group.

```
# Configure the header fields in a tab an all default node forms.
      setThirdPartySettings:
        - module: field_group
          key: group_summary
          value:
            children:
              - sa_description
              - sa_featured_media
              - sa_overlay
              - sa_header_position
              - sa_hide_header
              - sa_include_mute_button
              - sa_include_pause_button
            label: 'Summary'
            region: content
            # Assumes we have the parent Tabs.
            parent_name: group_administration
            weight: -99
            format_type: tab
            format_settings:
              classes: ''
              show_empty_fields: false
              id: ''
              formatter: closed
              description: ''
              required_fields: true
```

-----------

## Lets make the changes

1. In the composer.json file, require the recipes.
```
      "kanopi/saplings-fields-header": "^1",
      "kanopi/saplings-fields-seo": "^1"
```
In the recipe.yml make the following changes.

2. Add the recipes to be applied:
```
recipes:
  - saplings-fields-header
  - saplings-fields-seo
```

3. Delete configs from the config folder in this recipe.  The ones we don't need are:

```
    # Header
    - field.storage.node.sa_description
    - field.storage.node.sa_featured_media
    - field.storage.node.sa_header_position
    - field.storage.node.sa_hide_header
    - field.storage.node.sa_include_mute_button
    - field.storage.node.sa_include_pause_button
    - field.storage.node.sa_overlay
    - field.field.node.program.sa_description
    - field.field.node.program.sa_featured_media
    - field.field.node.program.sa_header_position
    - field.field.node.program.sa_hide_header
    - field.field.node.program.sa_include_mute_button
    - field.field.node.program.sa_include_pause_button
    - field.field.node.program.sa_overlay
    # SEO
    - field.storage.node.sa_robots
    - field.storage.node.sa_seo_description
    - field.storage.node.sa_seo_image
    - field.storage.node.sa_page_title
    - field.field.node.program.sa_robots
    - field.field.node.program.sa_seo_description
    - field.field.node.program.sa_seo_image
    - field.field.node.program.sa_page_title
```
